// DEFINES //

#define MENU_FILE_EXIT WM_USER+100
#define MENU_FILE_NEW WM_USER+101
#define MENU_FILE_OPEN WM_USER+102
#define MENU_FILE_SAVE WM_USER+103
#define MENU_FILE_SAVEAS WM_USER+104

#define MENU_DRAW_CHOOSE_COLOR_1 WM_USER+105
#define MENU_DRAW_CHOOSE_COLOR_2 WM_USER+106
#define MENU_DRAW_DRAW WM_USER+107

// END //

